apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: yaopods.k8s.liuyao.me
spec:
  group: k8s.liuyao.me
  names:
    kind: YaoPod
    listKind: YaoPodList
    plural: yaopods
    singular: yaopod
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: YaoPod is the Schema for the yaopods API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: YaoPodSpec defines the desired state of YaoPod
          type: object
        status:
          description: YaoPodStatus defines the observed state of YaoPod
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
