# permissions for end users to edit virtulmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtulmachine-editor-role
rules:
- apiGroups:
  - infra.me.liuyao
  resources:
  - virtulmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - infra.me.liuyao
  resources:
  - virtulmachines/status
  verbs:
  - get
