# permissions for end users to view virtulmachines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtulmachine-viewer-role
rules:
- apiGroups:
  - infra.me.liuyao
  resources:
  - virtulmachines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.me.liuyao
  resources:
  - virtulmachines/status
  verbs:
  - get
