apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pod-server-sts
  namespace: default
spec:
  selector:
    matchLabels:
      app: pod-server-sts
  replicas: 2
  serviceName: pod-server-sts
  template:
    metadata:
      labels:
        app: pod-server-sts
    spec:
      containers:
        - name: go-pod-server
          image: liuyao/go-pod-server:metrics
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-port
          resources:
            requests:
              cpu: 200m
