apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-php-apache
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Value
          value: '50'
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: '10'
#  behavior:
#    scaleUp:
#      selectPolicy:
#      stabilizationWindowSeconds:
#    scaleDown:
#      stabilizationWindowSeconds:
#      selectPolicy:
