apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pod-server
spec:
  selector:
    matchLabels:
      app: go-pod-server
  replicas: 2
  template:
    metadata:
      labels:
        app: go-pod-server
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: go-pod-server
          image: liuyao/go-pod-server:metrics
          imagePullPolicy: Always
          ports:
            - containerPort: 9100
              name: http-port
      volumes:
        - name: metadata
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations

