---
apiVersion: v1
kind: Service
metadata:
  name: go-pod-server
  labels:
    app: go-pod-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30304
      protocol: TCP
  selector:
    app: go-pod-server