---
apiVersion: v1
kind: Service
metadata:
  name: go-pod-server
  labels:
    app: go-pod-server
spec:
  type: NodePort
  ports:
    - port: 9100
      targetPort: 9100
      nodePort: 39100
      protocol: TCP
  selector:
    app: go-pod-server